services:
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Meiirzhan05!
      MYSQL_DATABASE: smilexah_db
      MYSQL_USER: root
      MYSQL_PASSWORD: Meiirzhan05!
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mysql_network
    restart: unless-stopped

  adminer:
    container_name: adminer
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - "8080:8080"
    networks:
      - mysql_network
    restart: unless-stopped

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - zipkin_network
    restart: unless-stopped

networks:
  mysql_network:
    driver: bridge
  zipkin_network:
    driver: bridge

volumes:
  mysql_data:
