spring:
  application:
    name: students
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/students
    username: root
    password: Meiirzhan05!
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
server:
  port: 8090

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
